// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package app

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for RemoteRuntime
func (this *RemoteRuntime) MarshalJSON() ([]byte, error) {
	str, err := AppMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RemoteRuntime
func (this *RemoteRuntime) UnmarshalJSON(b []byte) error {
	return AppUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for DebugToolBuilder
func (this *DebugToolBuilder) MarshalJSON() ([]byte, error) {
	str, err := AppMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for DebugToolBuilder
func (this *DebugToolBuilder) UnmarshalJSON(b []byte) error {
	return AppUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RemoteConfig
func (this *RemoteConfig) MarshalJSON() ([]byte, error) {
	str, err := AppMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RemoteConfig
func (this *RemoteConfig) UnmarshalJSON(b []byte) error {
	return AppUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for LocalConfig
func (this *LocalConfig) MarshalJSON() ([]byte, error) {
	str, err := AppMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for LocalConfig
func (this *LocalConfig) UnmarshalJSON(b []byte) error {
	return AppUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for App
func (this *App) MarshalJSON() ([]byte, error) {
	str, err := AppMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for App
func (this *App) UnmarshalJSON(b []byte) error {
	return AppUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Status
func (this *Status) MarshalJSON() ([]byte, error) {
	str, err := AppMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Status
func (this *Status) UnmarshalJSON(b []byte) error {
	return AppUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SingleAppRequest
func (this *SingleAppRequest) MarshalJSON() ([]byte, error) {
	str, err := AppMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SingleAppRequest
func (this *SingleAppRequest) UnmarshalJSON(b []byte) error {
	return AppUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for AppList
func (this *AppList) MarshalJSON() ([]byte, error) {
	str, err := AppMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AppList
func (this *AppList) UnmarshalJSON(b []byte) error {
	return AppUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Empty
func (this *Empty) MarshalJSON() ([]byte, error) {
	str, err := AppMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Empty
func (this *Empty) UnmarshalJSON(b []byte) error {
	return AppUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ServerInfo
func (this *ServerInfo) MarshalJSON() ([]byte, error) {
	str, err := AppMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ServerInfo
func (this *ServerInfo) UnmarshalJSON(b []byte) error {
	return AppUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	AppMarshaler   = &jsonpb.Marshaler{}
	AppUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
